### ISSUE TITLE
Linux/Mac error - factory.png vs Factory.png

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-maps/atari#1]
triplea.engine.version.bin:1.8.0.9
Exception: Cant load: Factory  looking in: units/Americans/Factory.png
games.strategy.triplea.image.UnitImageFactory.getBaseImageURL(UnitImageFactory.java:146)
games.strategy.triplea.image.UnitImageFactory.getBaseImageURL(UnitImageFactory.java:137)
games.strategy.triplea.image.UnitImageFactory.getBaseImage(UnitImageFactory.java:152)
games.strategy.triplea.image.UnitImageFactory.getImage(UnitImageFactory.java:117)
games.strategy.triplea.ui.screen.UnitsDrawer.draw(UnitsDrawer.java:77)
games.strategy.triplea.ui.screen.Tile.draw(Tile.java:122)
games.strategy.triplea.ui.screen.Tile.getImage(Tile.java:78)
games.strategy.triplea.ui.BackgroundDrawer.run(MapPanel.java:983)
java.lang.Thread.run(Thread.java:745)

**Comment by DanVanAtta** [comment]
> MISSING IMAGE (this unit or image will be invisible): UnitType{name=Factory}
> MISSING IMAGE (this unit or image will be invisible): UnitType{name=Factory}

Yup, still a problem. Though we probably could use an update to the error message to include the player name

**Comment by CharlieAtlas** [comment]
Added a Factory.png to Americans unit list
